# Generated by Django 6.0 on 2025-12-28 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=512)),
                ('biografia', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_utilizador', models.CharField(max_length=512)),
                ('email', models.CharField(max_length=512, unique=True)),
                ('password', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=512)),
                ('ano_lancamento', models.BigIntegerField()),
                ('genero', models.CharField(blank=True, max_length=512, null=True)),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albuns', to='biblioteca.artista')),
            ],
        ),
        migrations.CreateModel(
            name='MusicaEstatistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=512)),
                ('duracao', models.BigIntegerField()),
                ('url', models.CharField(max_length=512, unique=True)),
                ('estatistica_visualizacoes', models.BigIntegerField(default=0)),
                ('estatistica_gostos', models.BigIntegerField(default=0)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musicas_estatisticas', to='biblioteca.album')),
                ('artistas', models.ManyToManyField(db_table='artista_musica_estatistica', related_name='musicas_estatisticas', to='biblioteca.artista')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('publica', models.BooleanField()),
                ('data_criacao', models.DateField()),
                ('musica', models.ManyToManyField(blank=True, db_table='playlist_musica_estatistica', related_name='musicas_estatisticas', to='biblioteca.musicaestatistica')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='biblioteca.utilizador')),
            ],
        ),
    ]
