# Generated by Django 5.2.8 on 2025-12-28 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name': 'Álbum', 'verbose_name_plural': 'Álbuns'},
        ),
        migrations.AlterModelOptions(
            name='artista',
            options={'verbose_name': 'Artista', 'verbose_name_plural': 'Artistas'},
        ),
        migrations.AlterModelOptions(
            name='musicaestatistica',
            options={'verbose_name': 'Música', 'verbose_name_plural': 'Músicas'},
        ),
        migrations.AlterModelOptions(
            name='playlist',
            options={'verbose_name': 'Playlist', 'verbose_name_plural': 'Playlists'},
        ),
        migrations.AlterModelOptions(
            name='utilizador',
            options={'verbose_name': 'Utilizador', 'verbose_name_plural': 'Utilizadores'},
        ),
    ]
