# Generated by Django 5.2.8 on 2025-12-29 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_alter_album_options_alter_artista_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='data_criacao',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='musica',
            field=models.ManyToManyField(blank=True, db_table='playlist_musica_estatistica', related_name='playlists', to='biblioteca.musicaestatistica'),
        ),
    ]
