# Generated by Django 5.2.8 on 2025-12-29 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_alter_playlist_data_criacao_alter_playlist_musica'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='musica',
            new_name='musicas',
        ),
    ]
