# Generated by Django 4.2.27 on 2026-01-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_rename_musica_playlist_musicas'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='albuns/'),
        ),
        migrations.AddField(
            model_name='artista',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='artistas/'),
        ),
    ]
